package seeds

import "github.com/bookpanda/angryfern-backend/internal/model"

var Countries = []model.Score{
	{Code: "BD", CountryName: "Bangladesh", ClickCount: 0},
	{Code: "BE", CountryName: "Belgium", ClickCount: 0},
	{Code: "BF", CountryName: "Burkina Faso", ClickCount: 0},
	{Code: "BG", CountryName: "Bulgaria", ClickCount: 0},
	{Code: "BA", CountryName: "Bosnia and Herzegovina", ClickCount: 0},
	{Code: "BB", CountryName: "Barbados", ClickCount: 0},
	{Code: "WF", CountryName: "Wallis and Futuna", ClickCount: 0},
	{Code: "BL", CountryName: "Saint Barthelemy", ClickCount: 0},
	{Code: "BM", CountryName: "Bermuda", ClickCount: 0},
	{Code: "BN", CountryName: "Brunei", ClickCount: 0},
	{Code: "BO", CountryName: "Bolivia", ClickCount: 0},
	{Code: "BH", CountryName: "Bahrain", ClickCount: 0},
	{Code: "BI", CountryName: "Burundi", ClickCount: 0},
	{Code: "BJ", CountryName: "Benin", ClickCount: 0},
	{Code: "BT", CountryName: "Bhutan", ClickCount: 0},
	{Code: "JM", CountryName: "Jamaica", ClickCount: 0},
	{Code: "BV", CountryName: "Bouvet Island", ClickCount: 0},
	{Code: "BW", CountryName: "Botswana", ClickCount: 0},
	{Code: "WS", CountryName: "Samoa", ClickCount: 0},
	{Code: "BQ", CountryName: "Bonaire, Saint Eustatius and Saba ", ClickCount: 0},
	{Code: "BR", CountryName: "Brazil", ClickCount: 0},
	{Code: "BS", CountryName: "Bahamas", ClickCount: 0},
	{Code: "JE", CountryName: "Jersey", ClickCount: 0},
	{Code: "BY", CountryName: "Belarus", ClickCount: 0},
	{Code: "BZ", CountryName: "Belize", ClickCount: 0},
	{Code: "RU", CountryName: "Russia", ClickCount: 0},
	{Code: "RW", CountryName: "Rwanda", ClickCount: 0},
	{Code: "RS", CountryName: "Serbia", ClickCount: 0},
	{Code: "TL", CountryName: "East Timor", ClickCount: 0},
	{Code: "RE", CountryName: "Reunion", ClickCount: 0},
	{Code: "TM", CountryName: "Turkmenistan", ClickCount: 0},
	{Code: "TJ", CountryName: "Tajikistan", ClickCount: 0},
	{Code: "RO", CountryName: "Romania", ClickCount: 0},
	{Code: "TK", CountryName: "Tokelau", ClickCount: 0},
	{Code: "GW", CountryName: "Guinea-Bissau", ClickCount: 0},
	{Code: "GU", CountryName: "Guam", ClickCount: 0},
	{Code: "GT", CountryName: "Guatemala", ClickCount: 0},
	{Code: "GS", CountryName: "South Georgia and the South Sandwich Islands", ClickCount: 0},
	{Code: "GR", CountryName: "Greece", ClickCount: 0},
	{Code: "GQ", CountryName: "Equatorial Guinea", ClickCount: 0},
	{Code: "GP", CountryName: "Guadeloupe", ClickCount: 0},
	{Code: "JP", CountryName: "Japan", ClickCount: 0},
	{Code: "GY", CountryName: "Guyana", ClickCount: 0},
	{Code: "GG", CountryName: "Guernsey", ClickCount: 0},
	{Code: "GF", CountryName: "French Guiana", ClickCount: 0},
	{Code: "GE", CountryName: "Georgia", ClickCount: 0},
	{Code: "GD", CountryName: "Grenada", ClickCount: 0},
	{Code: "GB", CountryName: "United Kingdom", ClickCount: 0},
	{Code: "GA", CountryName: "Gabon", ClickCount: 0},
	{Code: "SV", CountryName: "El Salvador", ClickCount: 0},
	{Code: "GN", CountryName: "Guinea", ClickCount: 0},
	{Code: "GM", CountryName: "Gambia", ClickCount: 0},
	{Code: "GL", CountryName: "Greenland", ClickCount: 0},
	{Code: "GI", CountryName: "Gibraltar", ClickCount: 0},
	{Code: "GH", CountryName: "Ghana", ClickCount: 0},
	{Code: "OM", CountryName: "Oman", ClickCount: 0},
	{Code: "TN", CountryName: "Tunisia", ClickCount: 0},
	{Code: "JO", CountryName: "Jordan", ClickCount: 0},
	{Code: "HR", CountryName: "Croatia", ClickCount: 0},
	{Code: "HT", CountryName: "Haiti", ClickCount: 0},
	{Code: "HU", CountryName: "Hungary", ClickCount: 0},
	{Code: "HK", CountryName: "Hong Kong", ClickCount: 0},
	{Code: "HN", CountryName: "Honduras", ClickCount: 0},
	{Code: "HM", CountryName: "Heard Island and McDonald Islands", ClickCount: 0},
	{Code: "VE", CountryName: "Venezuela", ClickCount: 0},
	{Code: "PR", CountryName: "Puerto Rico", ClickCount: 0},
	{Code: "PS", CountryName: "Palestinian Territory", ClickCount: 0},
	{Code: "PW", CountryName: "Palau", ClickCount: 0},
	{Code: "PT", CountryName: "Portugal", ClickCount: 0},
	{Code: "SJ", CountryName: "Svalbard and Jan Mayen", ClickCount: 0},
	{Code: "PY", CountryName: "Paraguay", ClickCount: 0},
	{Code: "IQ", CountryName: "Iraq", ClickCount: 0},
	{Code: "PA", CountryName: "Panama", ClickCount: 0},
	{Code: "PF", CountryName: "French Polynesia", ClickCount: 0},
	{Code: "PG", CountryName: "Papua New Guinea", ClickCount: 0},
	{Code: "PE", CountryName: "Peru", ClickCount: 0},
	{Code: "PK", CountryName: "Pakistan", ClickCount: 0},
	{Code: "PH", CountryName: "Philippines", ClickCount: 0},
	{Code: "PN", CountryName: "Pitcairn", ClickCount: 0},
	{Code: "PL", CountryName: "Poland", ClickCount: 0},
	{Code: "PM", CountryName: "Saint Pierre and Miquelon", ClickCount: 0},
	{Code: "ZM", CountryName: "Zambia", ClickCount: 0},
	{Code: "EH", CountryName: "Western Sahara", ClickCount: 0},
	{Code: "EE", CountryName: "Estonia", ClickCount: 0},
	{Code: "EG", CountryName: "Egypt", ClickCount: 0},
	{Code: "ZA", CountryName: "South Africa", ClickCount: 0},
	{Code: "EC", CountryName: "Ecuador", ClickCount: 0},
	{Code: "IT", CountryName: "Italy", ClickCount: 0},
	{Code: "VN", CountryName: "Vietnam", ClickCount: 0},
	{Code: "SB", CountryName: "Solomon Islands", ClickCount: 0},
	{Code: "ET", CountryName: "Ethiopia", ClickCount: 0},
	{Code: "SO", CountryName: "Somalia", ClickCount: 0},
	{Code: "ZW", CountryName: "Zimbabwe", ClickCount: 0},
	{Code: "SA", CountryName: "Saudi Arabia", ClickCount: 0},
	{Code: "ES", CountryName: "Spain", ClickCount: 0},
	{Code: "ER", CountryName: "Eritrea", ClickCount: 0},
	{Code: "ME", CountryName: "Montenegro", ClickCount: 0},
	{Code: "MD", CountryName: "Moldova", ClickCount: 0},
	{Code: "MG", CountryName: "Madagascar", ClickCount: 0},
	{Code: "MF", CountryName: "Saint Martin", ClickCount: 0},
	{Code: "MA", CountryName: "Morocco", ClickCount: 0},
	{Code: "MC", CountryName: "Monaco", ClickCount: 0},
	{Code: "UZ", CountryName: "Uzbekistan", ClickCount: 0},
	{Code: "MM", CountryName: "Myanmar", ClickCount: 0},
	{Code: "ML", CountryName: "Mali", ClickCount: 0},
	{Code: "MO", CountryName: "Macao", ClickCount: 0},
	{Code: "MN", CountryName: "Mongolia", ClickCount: 0},
	{Code: "MH", CountryName: "Marshall Islands", ClickCount: 0},
	{Code: "MK", CountryName: "Macedonia", ClickCount: 0},
	{Code: "MU", CountryName: "Mauritius", ClickCount: 0},
	{Code: "MT", CountryName: "Malta", ClickCount: 0},
	{Code: "MW", CountryName: "Malawi", ClickCount: 0},
	{Code: "MV", CountryName: "Maldives", ClickCount: 0},
	{Code: "MQ", CountryName: "Martinique", ClickCount: 0},
	{Code: "MP", CountryName: "Northern Mariana Islands", ClickCount: 0},
	{Code: "MS", CountryName: "Montserrat", ClickCount: 0},
	{Code: "MR", CountryName: "Mauritania", ClickCount: 0},
	{Code: "IM", CountryName: "Isle of Man", ClickCount: 0},
	{Code: "UG", CountryName: "Uganda", ClickCount: 0},
	{Code: "TZ", CountryName: "Tanzania", ClickCount: 0},
	{Code: "MY", CountryName: "Malaysia", ClickCount: 0},
	{Code: "MX", CountryName: "Mexico", ClickCount: 0},
	{Code: "IL", CountryName: "Israel", ClickCount: 0},
	{Code: "FR", CountryName: "France", ClickCount: 0},
	{Code: "IO", CountryName: "British Indian Ocean Territory", ClickCount: 0},
	{Code: "SH", CountryName: "Saint Helena", ClickCount: 0},
	{Code: "FI", CountryName: "Finland", ClickCount: 0},
	{Code: "FJ", CountryName: "Fiji", ClickCount: 0},
	{Code: "FK", CountryName: "Falkland Islands", ClickCount: 0},
	{Code: "FM", CountryName: "Micronesia", ClickCount: 0},
	{Code: "FO", CountryName: "Faroe Islands", ClickCount: 0},
	{Code: "NI", CountryName: "Nicaragua", ClickCount: 0},
	{Code: "NL", CountryName: "Netherlands", ClickCount: 0},
	{Code: "NO", CountryName: "Norway", ClickCount: 0},
	{Code: "NA", CountryName: "Namibia", ClickCount: 0},
	{Code: "VU", CountryName: "Vanuatu", ClickCount: 0},
	{Code: "NC", CountryName: "New Caledonia", ClickCount: 0},
	{Code: "NE", CountryName: "Niger", ClickCount: 0},
	{Code: "NF", CountryName: "Norfolk Island", ClickCount: 0},
	{Code: "NG", CountryName: "Nigeria", ClickCount: 0},
	{Code: "NZ", CountryName: "New Zealand", ClickCount: 0},
	{Code: "NP", CountryName: "Nepal", ClickCount: 0},
	{Code: "NR", CountryName: "Nauru", ClickCount: 0},
	{Code: "NU", CountryName: "Niue", ClickCount: 0},
	{Code: "CK", CountryName: "Cook Islands", ClickCount: 0},
	{Code: "XK", CountryName: "Kosovo", ClickCount: 0},
	{Code: "CI", CountryName: "Ivory Coast", ClickCount: 0},
	{Code: "CH", CountryName: "Switzerland", ClickCount: 0},
	{Code: "CO", CountryName: "Colombia", ClickCount: 0},
	{Code: "CN", CountryName: "China", ClickCount: 0},
	{Code: "CM", CountryName: "Cameroon", ClickCount: 0},
	{Code: "CL", CountryName: "Chile", ClickCount: 0},
	{Code: "CC", CountryName: "Cocos Islands", ClickCount: 0},
	{Code: "CA", CountryName: "Canada", ClickCount: 0},
	{Code: "CG", CountryName: "Republic of the Congo", ClickCount: 0},
	{Code: "CF", CountryName: "Central African Republic", ClickCount: 0},
	{Code: "CD", CountryName: "Democratic Republic of the Congo", ClickCount: 0},
	{Code: "CZ", CountryName: "Czech Republic", ClickCount: 0},
	{Code: "CY", CountryName: "Cyprus", ClickCount: 0},
	{Code: "CX", CountryName: "Christmas Island", ClickCount: 0},
	{Code: "CR", CountryName: "Costa Rica", ClickCount: 0},
	{Code: "CW", CountryName: "Curacao", ClickCount: 0},
	{Code: "CV", CountryName: "Cape Verde", ClickCount: 0},
	{Code: "CU", CountryName: "Cuba", ClickCount: 0},
	{Code: "SZ", CountryName: "Swaziland", ClickCount: 0},
	{Code: "SY", CountryName: "Syria", ClickCount: 0},
	{Code: "SX", CountryName: "Sint Maarten", ClickCount: 0},
	{Code: "KG", CountryName: "Kyrgyzstan", ClickCount: 0},
	{Code: "KE", CountryName: "Kenya", ClickCount: 0},
	{Code: "SS", CountryName: "South Sudan", ClickCount: 0},
	{Code: "SR", CountryName: "SuricountrCountryName", ClickCount: 0},
	{Code: "KI", CountryName: "Kiribati", ClickCount: 0},
	{Code: "KH", CountryName: "Cambodia", ClickCount: 0},
	{Code: "KN", CountryName: "Saint Kitts and Nevis", ClickCount: 0},
	{Code: "KM", CountryName: "Comoros", ClickCount: 0},
	{Code: "ST", CountryName: "Sao Tome and Principe", ClickCount: 0},
	{Code: "SK", CountryName: "Slovakia", ClickCount: 0},
	{Code: "KR", CountryName: "South Korea", ClickCount: 0},
	{Code: "SI", CountryName: "Slovenia", ClickCount: 0},
	{Code: "KP", CountryName: "North Korea", ClickCount: 0},
	{Code: "KW", CountryName: "Kuwait", ClickCount: 0},
	{Code: "SN", CountryName: "Senegal", ClickCount: 0},
	{Code: "SM", CountryName: "San Marino", ClickCount: 0},
	{Code: "SL", CountryName: "Sierra Leone", ClickCount: 0},
	{Code: "SC", CountryName: "Seychelles", ClickCount: 0},
	{Code: "KZ", CountryName: "Kazakhstan", ClickCount: 0},
	{Code: "KY", CountryName: "Cayman Islands", ClickCount: 0},
	{Code: "SG", CountryName: "Singapore", ClickCount: 0},
	{Code: "SE", CountryName: "Sweden", ClickCount: 0},
	{Code: "SD", CountryName: "Sudan", ClickCount: 0},
	{Code: "DO", CountryName: "Dominican Republic", ClickCount: 0},
	{Code: "DM", CountryName: "Dominica", ClickCount: 0},
	{Code: "DJ", CountryName: "Djibouti", ClickCount: 0},
	{Code: "DK", CountryName: "Denmark", ClickCount: 0},
	{Code: "VG", CountryName: "British Virgin Islands", ClickCount: 0},
	{Code: "DE", CountryName: "Germany", ClickCount: 0},
	{Code: "YE", CountryName: "Yemen", ClickCount: 0},
	{Code: "DZ", CountryName: "Algeria", ClickCount: 0},
	{Code: "US", CountryName: "United States", ClickCount: 0},
	{Code: "UY", CountryName: "Uruguay", ClickCount: 0},
	{Code: "YT", CountryName: "Mayotte", ClickCount: 0},
	{Code: "UM", CountryName: "United States Minor Outlying Islands", ClickCount: 0},
	{Code: "LB", CountryName: "Lebanon", ClickCount: 0},
	{Code: "LC", CountryName: "Saint Lucia", ClickCount: 0},
	{Code: "LA", CountryName: "Laos", ClickCount: 0},
	{Code: "TV", CountryName: "Tuvalu", ClickCount: 0},
	{Code: "TW", CountryName: "Taiwan", ClickCount: 0},
	{Code: "TT", CountryName: "Trinidad and Tobago", ClickCount: 0},
	{Code: "TR", CountryName: "Turkey", ClickCount: 0},
	{Code: "LK", CountryName: "Sri Lanka", ClickCount: 0},
	{Code: "LI", CountryName: "Liechtenstein", ClickCount: 0},
	{Code: "LV", CountryName: "Latvia", ClickCount: 0},
	{Code: "TO", CountryName: "Tonga", ClickCount: 0},
	{Code: "LT", CountryName: "Lithuania", ClickCount: 0},
	{Code: "LU", CountryName: "Luxembourg", ClickCount: 0},
	{Code: "LR", CountryName: "Liberia", ClickCount: 0},
	{Code: "LS", CountryName: "Lesotho", ClickCount: 0},
	{Code: "TH", CountryName: "Thailand", ClickCount: 0},
	{Code: "TF", CountryName: "French Southern Territories", ClickCount: 0},
	{Code: "TG", CountryName: "Togo", ClickCount: 0},
	{Code: "TD", CountryName: "Chad", ClickCount: 0},
	{Code: "TC", CountryName: "Turks and Caicos Islands", ClickCount: 0},
	{Code: "LY", CountryName: "Libya", ClickCount: 0},
	{Code: "VA", CountryName: "Vatican", ClickCount: 0},
	{Code: "VC", CountryName: "Saint Vincent and the Grenadines", ClickCount: 0},
	{Code: "AE", CountryName: "United Arab Emirates", ClickCount: 0},
	{Code: "AD", CountryName: "Andorra", ClickCount: 0},
	{Code: "AG", CountryName: "Antigua and Barbuda", ClickCount: 0},
	{Code: "AF", CountryName: "Afghanistan", ClickCount: 0},
	{Code: "AI", CountryName: "Anguilla", ClickCount: 0},
	{Code: "VI", CountryName: "U.S. Virgin Islands", ClickCount: 0},
	{Code: "IS", CountryName: "Iceland", ClickCount: 0},
	{Code: "IR", CountryName: "Iran", ClickCount: 0},
	{Code: "AM", CountryName: "Armenia", ClickCount: 0},
	{Code: "AL", CountryName: "Albania", ClickCount: 0},
	{Code: "AO", CountryName: "Angola", ClickCount: 0},
	{Code: "AQ", CountryName: "Antarctica", ClickCount: 0},
	{Code: "AS", CountryName: "American Samoa", ClickCount: 0},
	{Code: "AR", CountryName: "Argentina", ClickCount: 0},
	{Code: "AU", CountryName: "Australia", ClickCount: 0},
	{Code: "AT", CountryName: "Austria", ClickCount: 0},
	{Code: "AW", CountryName: "Aruba", ClickCount: 0},
	{Code: "IN", CountryName: "India", ClickCount: 0},
	{Code: "AX", CountryName: "Aland Islands", ClickCount: 0},
	{Code: "AZ", CountryName: "Azerbaijan", ClickCount: 0},
	{Code: "IE", CountryName: "Ireland", ClickCount: 0},
	{Code: "ID", CountryName: "Indonesia", ClickCount: 0},
	{Code: "UA", CountryName: "Ukraine", ClickCount: 0},
	{Code: "QA", CountryName: "Qatar", ClickCount: 0},
	{Code: "MZ", CountryName: "Mozambique", ClickCount: 0},
}
