version: "3.9"

services:
  db:
    container_name: angryfern-db
    image: postgres:15.1-alpine3.17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=angryfern_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - angryfern

  backend:
    container_name: angryfern-backend
    image: ghcr.io/bookpanda/angryfern-backend
    depends_on:
      - db
    ports:
      - 3001:3000
    environment:
      - APP_PORT=3000
      - APP_ENV=development
      - APP_API_KEY=key
      - DB_URL=postgres://root:1234@angryfern-db:5432/angryfern_db
      - CORS_ORIGINS=http://localhost:3000
    networks:
      - angryfern


networks:
  angryfern: 
